### ISSUE TITLE
Range values? ( MapTweaks & DetectionRange )

### ISSUE THREAD

**Issue by x33st0rm** [AlexTheRegent/tld-GameTweaks#1]
I'd love to use these mods, but they are all set to disabled by default in the xml's, and i have no clue what the value ranges are, unless i tried them all out by trial and error.

Could you please add some information to them?

Are they meters or feet, or just arbitrary?
What are the default values, what is high and what is low?

Thanks.

**Comment by JoESmash** [comment]
Same problem with the detection range one.....wth do you change things to to lets say double all detection ranges?

A little info on example values would be helpful....

**Comment by AlexTheRegent** [comment]
Added default values in 1.0.6 version.
