### ISSUE TITLE
Map Tweaks not working

### ISSUE THREAD

**Issue by Johnny5X** [AlexTheRegent/tld-GameTweaks#2]
So i downloaded and installed your mod but it seems that it is deactivated.Is there any way to fix it?

**Comment by videosegments** [comment]
Hi!
By default mod does nothing. You have to change settings (path/to/TheLongDark/mods/MapTweaks.xml). Open this file with notepad (or any other text editor) and change values, save file and restart game (save&exit and load, no need to start new game).
I'm working on mod settings page ingame, but I dont know when I'll be able to finish (I want to move all my plugins to ingame mods settings).

**Comment by Johnny5X** [comment]
Thanks for replying, so I got it to do the auto-mapping but I still can change the drawing range. I tried putting 2, 5 and 10 in the drawingrangevalue instead of -1 but nothing changes.

**Comment by AlexTheRegent** [comment]
Try to set relative high values, about 1000 should give visible changes.
<drawing_range value="1000"/>
This is related to #1 and I will try to add game settings as default settings to all my mods if possible.
P.S. Forgot to change account in previous comment :)

**Comment by Johnny5X** [comment]
Ok problem solved thanks 😃👍

**Comment by AlexTheRegent** [comment]
Added default values in 1.0.6 version.
