### ISSUE TITLE
Beta version of FasterActionRedux breaks plant harvesting

### ISSUE THREAD

**Issue by TheWyrdsmith** [AlexTheRegent/tld-GameTweaks#5]
Many thanks for these mods! I've been using the beta versions of MapTweaks, SkipIntro, StruggleTweaks and WeaponCrosshair from the zip you linked in issue 4 without any issues.

However, I would like to let you know that the beta of FasterActionRedux (a super useful mod!) removes the ability to harvest plants. The timing bar fills up and the object is removed from the game world, but it is not added to the inventory and no 'take it/leave it' screen appears. This happens with action speeds of 0.06, at 0.5, and at 1.0. At least birch and maple saplings, rose hips, cat tails and old man's beard are affected. Reproducible on latest Steam version with only this mod and the developer console mod.

**Comment by TheWyrdsmith** [comment]
I copied out your code for plant harvesting to see if I could create a fix for it and it appears that the postfix modification you have for clearing hover text (Harvestable.CompletedHarvest) is no longer required (at least down to action speeds of 0.25). Removing this patch allowed harvesting plants once more.

**Comment by AlexTheRegent** [comment]
Hi! Sorry for late response.
Yes, you right. According to DeveloperConsole mod, they removed (or renamed) _m_Panel_HUD.SetHoverText_ method. Thank you for your report!
I will upload here updated version (including your fix) + beta of DetectionRange.
https://mega.nz/#!qyZlBKAQ!j8ay_o2Bi-S6rgUTgL_6c_N7Z7P2lJdpFKDKTUIqXmQ
P.S. I also recommend you to try TimeAccelerator, it works in same way as FasterActionRedux but manually thus allowing you to travel faster without cheating in any way.

**Comment by AlexTheRegent** [comment]
Fixed in v1.0.6.
